AllCops:
  # .ruby-version の指定と合わせるため指定しない
  # TargetRubyVersion: ~
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/spring'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'

Rails:
  Enabled: true

Metrics/ClassLength:
  CountComments: false
  Max: 150

Metrics/ModuleLength:
  CountComments: false
  Max: 130

Metrics/LineLength:
  Max: 250
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  Max: 40
  Exclude:
    # データ移行のためにSQLを書くことがあるため許容する
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 9

Naming/AccessorMethodName:
  Exclude:
    # # action_args を使うため
    # before_action :set_user
    #
    # def set_user(id)
    #   @user = User.find(id)
    # end
    - '**/*_controller.rb'
    - 'app/controllers/concerns/**/*.rb'

# # 宗教の違いを許容する
# def some_method_with_parameters param1, param2
#  # body omitted
# end
#
# def some_method_with_parameters(param1, param2)
#  # body omitted
# end
Style/MethodDefParentheses:
  Enabled: false

# 日本語コメントを許容する
Style/AsciiComments:
  Enabled: false

Style/LambdaCall:
  Exclude:
    # # jbuilder の README の通りに書いても検出されるため
    # json.(@message, :created_at, :updated_at)
    - '**/*.jbuilder'

# # consistent
# hash = {
#   key: :value
# }
# and_in_a_method_call({
#   no: :difference
# })
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

# ドキュメントの無い public クラスを許容する
Style/Documentation:
  Enabled: false

# email など NOT NULL でもデフォルト値を指定できないカラムは存在する
Rails/NotNullColumn:
  Enabled: false

# map...flatten はだいたい flat_map に直せるのでチェックしておく
Performance/FlatMap:
  EnabledForFlattenWithoutParams: true

# alias, alias_method で細かい挙動が変わるため、使い分ける必要がある
#
# 参考: http://blog.bigbinary.com/2012/01/08/alias-vs-alias-method.html
Style/Alias:
  Enabled: false

# - Emacs のデフォルトが with_first_parameter
# - Vim のデフォルトが with_fixed_indentation
#
# という宗教の違いを許容する
Layout/AlignParameters:
  Enabled: false

# データ移行のために execute を使うことがあるため許容する
Rails/ReversibleMigration:
  Enabled: false

# typo に気付けるようにするため
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

# 子レコードを残しておきたい場合もあるため許容する
Rails/HasManyOrHasOneDependent:
  Enabled: false
