# These are the cops before discussion in Forkwell team.

Lint/EnsureReturn:
  Enabled: true

Lint/Eval:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Validation:
  Enabled: false

Style/Alias:
  Enabled: true

Style/AlignParameters:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/VariableNumber:
  Enabled: false

Style/GuardClause:
  Enabled: false

# v0.44.0
Metrics/BlockLength:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

# v0.45.0
Style/MultilineIfModifier:
  Enabled: false

Style/SpaceInLambdaLiteral:
  Enabled: false
